### PR TITLE
Allowing controller to access secrets

### PR DESCRIPTION
**Pull request by Red-GV**
Adding the secrets to the RBAC role for the controller.

### CODE REVIEW

**Comment by periklis** [comment]
> Adding the secrets to the RBAC role for the controller.

As per not reconciling owned secrets, I recommend to add a more fine-grained rule for secrets allowing only `get,watch,list`.

**Comment by Red-GV** [comment]
Should be good to go now, @periklis. Thanks!

**Review by periklis — APPROVED** [review]
LGTM

**Pull request merged**
